version: "3.9"
services:
  backend:
    build: ./backend
    command: bash -c "python manage.py migrate && python manage.py collectstatic --no-input --clear && python manage.py runserver  0.0.0.0:8000"   
    ports:
      - "8000:8000"
    volumes:
      - static:/code/static_root
      - media:/code/media
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings
    depends_on:
      - db


  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
      - "24678:24678" # HMR用のポートを追加
    command: bash -c "yarn dev"
    environment:
      - API_BASE_URL=/api
