version: "3.9"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx_conf:/etc/nginx/conf.d
      - static:/code/static_root
      - media:/code/media

    depends_on:
      - backend
      - frontend


volumes:
  static:
  media: